spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springbootvue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
